name: tbaleqa
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - trl>=0.7.0
    - transformers>=4.30.0
    - torch>=2.0.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - peft>=0.4.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    - tqdm>=4.65.0
    - jupyter>=1.0.0
    - ipywidgets>=8.0.0
    - gymnasium>=0.28.0
    - stable-baselines3>=2.0.0

